// <auto-generated />
using System;
using EcommerceSqlSolutions.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceSqlSolutions.Migrations
{
    [DbContext(typeof(EcommerceContext))]
    [Migration("20260320111728_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("EcommerceSqlSolutions.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("EcommerceSqlSolutions.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("EcommerceSqlSolutions.Models.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("EcommerceSqlSolutions.Models.GoodProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Bdate")
                        .HasColumnType("date");

                    b.Property<int>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Edate")
                        .HasColumnType("date");

                    b.Property<int>("GoodId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("GoodId");

                    b.ToTable("GoodProperties");
                });

            modelBuilder.Entity("EcommerceSqlSolutions.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EcommerceSqlSolutions.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoodCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GoodId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails", t =>
                        {
                            t.HasCheckConstraint("CK_OrderDetail_GoodCount", "GoodCount > 0");
                        });
                });

            modelBuilder.Entity("EcommerceSqlSolutions.Models.GoodProperty", b =>
                {
                    b.HasOne("EcommerceSqlSolutions.Models.Color", "Color")
                        .WithMany("GoodProperties")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceSqlSolutions.Models.Good", "Good")
                        .WithMany("GoodProperties")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Good");
                });

            modelBuilder.Entity("EcommerceSqlSolutions.Models.Order", b =>
                {
                    b.HasOne("EcommerceSqlSolutions.Models.Agent", "Agent")
                        .WithMany("Orders")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("EcommerceSqlSolutions.Models.OrderDetail", b =>
                {
                    b.HasOne("EcommerceSqlSolutions.Models.Good", "Good")
                        .WithMany("OrderDetails")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceSqlSolutions.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Good");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EcommerceSqlSolutions.Models.Agent", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EcommerceSqlSolutions.Models.Color", b =>
                {
                    b.Navigation("GoodProperties");
                });

            modelBuilder.Entity("EcommerceSqlSolutions.Models.Good", b =>
                {
                    b.Navigation("GoodProperties");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("EcommerceSqlSolutions.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
